disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - colon
  - comma
  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  # Find all the available rules by running:
  # swiftlint rules
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - BankAppSwiftUI/Generated
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly

force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  
identifier_name:
  min_length: # only min_length
    warning: 3
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    
cyclomatic_complexity:
    warning: 15
    error: 25
    
reporter: "xcode"
